# Generated by Django 3.0.5 on 2021-11-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AeroBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_img', models.ImageField(upload_to='aero/images')),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('paragraph3', models.TextField()),
                ('paragraph4', models.TextField()),
                ('paragraph5', models.TextField()),
                ('img', models.ImageField(upload_to='aero/images/')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('happeningdate', models.DateTimeField()),
                ('smalldescription', models.TextField()),
                ('largedescription', models.TextField()),
                ('imagelink', models.CharField(max_length=500)),
                ('drivelink', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
