# Generated by Django 3.0.5 on 2022-11-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeroblog',
            name='cover_img',
            field=models.ImageField(upload_to='aero_club\x07ero\\img'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='aero_club\x07ero\\img'),
        ),
    ]
